
version: "3"
services:
  redis-docker:
    image: redis:latest
    command: redis-server --port 6379
    container_name: "docker-redis"
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379

services:
  api-swagger:
    image: swaggerapi/swagger-ui
    container_name: api-swagger
    ports:
      - 8080:8080
    environment:
      API_URL: {URL}:8080/api/swagger-ui.html
