
version: '3'
services:
  nginx:
    image:
      nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./nginx/nginx:/etc/nginx.conf.d
    # 시작순서제어 - nginx 컨테이너 시작 전 web 컨테이너 시작 
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn backend.wsqi.application --bind 0.0.0.0:8000

    volumes:
      - .:/code
    ports:
      - "8000:8000"
